<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { adminGetWeatherLocations, adminCreateWeatherLocation, adminUpdateWeatherLocation, adminDeleteWeatherLocation, type AdminWeatherLocation } from '@/api/admin-weather'
import { ElMessage, ElMessageBox } from 'element-plus'
const locs = ref<AdminWeatherLocation[]>([]); const loading = ref(false)
async function load() { loading.value = true; try { locs.value = await adminGetWeatherLocations() } finally { loading.value = false } }
const dlg = ref(false); const dlgEditId = ref<number|null>(null); const dlgLoading = ref(false)
const form = reactive({ locationName: '', locationType: 'scenic', scenicSpotId: 0 as number, updateEnabled: 0, sortOrder: 0, status: 1, providerCode: 'amap' })
function openNew() { dlgEditId.value = null; Object.assign(form, { locationName: '', locationType: 'scenic', scenicSpotId: 0, updateEnabled: 0, sortOrder: 0, status: 1, providerCode: 'amap' }); dlg.value = true }
function openEdit(l: AdminWeatherLocation) { dlgEditId.value = l.id; form.locationName = l.locationName; form.locationType = l.locationType||'scenic'; form.scenicSpotId = l.scenicSpotId||0; form.updateEnabled = l.updateEnabled??0; form.sortOrder = l.sortOrder??0; form.status = l.status??1; form.providerCode = l.providerCode||'amap'; dlg.value = true }
async function onSave() { if (!form.locationName.trim()) { ElMessage.warning('地点名称不能为空'); return }; dlgLoading.value = true; try { dlgEditId.value ? await adminUpdateWeatherLocation(dlgEditId.value, form) : await adminCreateWeatherLocation(form); ElMessage.success('保存成功'); dlg.value = false; load() } finally { dlgLoading.value = false } }
async function onToggle(l: AdminWeatherLocation) { const s = l.status===1?0:1; await adminUpdateWeatherLocation(l.id,{status:s}); l.status = s; ElMessage.success('操作成功') }
async function onDel(l: AdminWeatherLocation) { try{await ElMessageBox.confirm(`删除「${l.locationName}」？`,'确认',{type:'warning'})}catch{return}; await adminDeleteWeatherLocation(l.id); ElMessage.success('已删除'); load() }
const sMap: Record<number,{t:''|'success'|'info';tx:string}> = { 1:{t:'success',tx:'启用'}, 0:{t:'info',tx:'停用'} }
onMounted(()=>{ load() })
</script>
<template><div><div class="ph"><h2 class="pt">天气管理</h2><div class="ha"><el-button @click="load">刷新</el-button><el-button type="success" @click="openNew">新增地点</el-button></div></div>
<el-card shadow="never"><el-table :data="locs" v-loading="loading" stripe><el-table-column prop="id" label="ID" width="60"/><el-table-column prop="locationName" label="地点名称" min-width="140"/><el-table-column prop="locationType" label="类型" width="80"/><el-table-column prop="scenicSpotId" label="景点ID" width="80"/><el-table-column prop="providerCode" label="源" width="70"/><el-table-column label="更新" width="70"><template #default="{row}"><el-tag :type="row.updateEnabled?'success':'info'" size="small">{{ row.updateEnabled?'开启':'关闭' }}</el-tag></template></el-table-column><el-table-column prop="sortOrder" label="排序" width="70"/><el-table-column label="状态" width="80"><template #default="{row}"><el-tag :type="sMap[row.status]?.t||'info'" size="small">{{ sMap[row.status]?.tx }}</el-tag></template></el-table-column><el-table-column label="操作" width="160"><template #default="{row}"><el-button text type="primary" size="small" @click="openEdit(row)">编辑</el-button><el-button text size="small" @click="onToggle(row)">{{ row.status===1?'停用':'启用' }}</el-button><el-button text type="danger" size="small" @click="onDel(row)">删除</el-button></template></el-table-column></el-table>
<div v-if="!loading&&locs.length===0" class="eh">暂无数据</div></el-card>
<el-dialog v-model="dlg" :title="dlgEditId?'编辑':'新增'" width="500px" :close-on-click-modal="false" destroy-on-close>
<el-form :model="form" label-width="80px"><el-form-item label="名称" required><el-input v-model="form.locationName"/></el-form-item>
<el-row :gutter="16"><el-col :span="12"><el-form-item label="类型"><el-select v-model="form.locationType" style="width:100%"><el-option label="景区" value="scenic"/><el-option label="路线" value="route"/><el-option label="城市" value="city"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="景点ID"><el-input-number v-model="form.scenicSpotId" :min="0"/></el-form-item></el-col></el-row>
<el-row :gutter="16"><el-col :span="12"><el-form-item label="源"><el-input v-model="form.providerCode"/></el-form-item></el-col><el-col :span="12"><el-form-item label="更新"><el-switch v-model="form.updateEnabled" :active-value="1" :inactive-value="0"/></el-form-item></el-col></el-row>
<el-row :gutter="16"><el-col :span="12"><el-form-item label="排序"><el-input-number v-model="form.sortOrder" :min="0" :max="999"/></el-form-item></el-col><el-col :span="12"><el-form-item label="状态"><el-switch v-model="form.status" :active-value="1" :inactive-value="0" active-text="启用" inactive-text="停用"/></el-form-item></el-col></el-row></el-form>
<template #footer><el-button @click="dlg=false">取消</el-button><el-button type="primary" :loading="dlgLoading" @click="onSave">保存</el-button></template></el-dialog></div></template>
<style scoped>.ph{display:flex;align-items:center;justify-content:space-between;margin-bottom:20px;flex-wrap:wrap;gap:12px}.pt{font-size:22px;font-weight:700;color:#303133}.ha{display:flex;gap:10px;align-items:center}.eh{text-align:center;color:#909399;padding:40px 0}</style>
